### ISSUE TITLE
console warning: Incorrect use of <label for=FORM_ELEMENT>

### ISSUE THREAD

**Issue by kaden-weber** [ManhanGroup/calbuilds#46]
There are several \<label> tags that aren't actually associated with a form element that are making the console complain. It would probably be easiest to just use a different tag.

**Comment by purpleplum** [comment]
Just going through the list of issues and saw this. I saw the error message for the first time last week and either added id to form element or removed the for=FORM_ELEMENT from the label tag. For the time being, the error messages are gone.
