### ISSUE TITLE
fix logo sizes in the user panel footer

### ISSUE THREAD

**Issue by kaden-weber** [ManhanGroup/calbuilds#57]

**Comment by kaden-weber** [comment]
Also note that the logos are queried with each switch of the view... could be optimized as it clogs up the console. (I also think this might be a regression from the addition of the new agency.)

**Comment by purpleplum** [comment]
The width needs to be limited. Otherwise, it doesn't look good in firefox:

![image](https://github.com/ManhanGroup/calbuilds/assets/1187762/ae3a51ac-c928-4445-9206-96f102adf2c4)
